# Generated by Django 3.0.5 on 2020-04-14 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('update', models.DateTimeField()),
                ('hour_tendency', models.IntegerField()),
                ('hour_tendency_var', models.IntegerField()),
                ('day_tendency', models.IntegerField()),
                ('day_tendency_var', models.IntegerField()),
                ('week_tendency', models.IntegerField()),
                ('week_tendency_var', models.IntegerField()),
                ('month_tendency', models.IntegerField()),
                ('month_tendency_var', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=1)),
                ('phone', models.CharField(default='09125459232', max_length=11)),
                ('last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 4, 14, 7, 42, 6, 58511, tzinfo=utc))),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Material')),
            ],
        ),
    ]
