# Generated by Django 3.0.5 on 2020-04-14 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='day_tendency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='day_tendency_var',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='hour_tendency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='hour_tendency_var',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='month_tendency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='month_tendency_var',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='week_tendency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='week_tendency_var',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
