# Generated by Django 2.2.12 on 2020-04-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200414_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theUrl', models.URLField()),
                ('kind', models.CharField(default='li', max_length=10)),
                ('the_id', models.CharField(default='', max_length=100)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Material')),
            ],
        ),
    ]
