# Generated by Django 2.2.12 on 2020-04-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_wrapper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrapper',
            old_name='theUrl',
            new_name='the_url',
        ),
    ]
