# Generated by Django 2.2.12 on 2020-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200414_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='the_url',
            field=models.URLField(default='https://www.tgju.org'),
        ),
    ]
