# Generated by Django 2.2.12 on 2020-04-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200414_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrapper',
            old_name='Material',
            new_name='material',
        ),
    ]
