# Generated by Django 2.2.12 on 2020-04-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200414_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='last_mail_date',
        ),
    ]
