# Generated by Django 2.2.12 on 2020-04-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200414_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('material1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Material')),
            ],
        ),
    ]
