# Generated by Django 2.2.12 on 2020-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_news_newswrapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='kind',
            field=models.IntegerField(default=0),
        ),
    ]
