# Generated by Django 2.2.12 on 2020-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200602_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_mail_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='speed',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='not@gmail.com', max_length=254),
        ),
    ]
