# Generated by Django 2.2.12 on 2020-06-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200607_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
