# Generated by Django 2.2.12 on 2020-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_material_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pure_gold_weight',
            field=models.FloatField(default=0),
        ),
    ]
