# Generated by Django 2.2.12 on 2020-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_material_pure_gold_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='bulb',
            field=models.IntegerField(default=0),
        ),
    ]
