# Generated by Django 2.2.12 on 2020-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_material_bulb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
