# Generated by Django 2.2.12 on 2020-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200608_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
